name: doan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cupertino_icons: ^1.0.2
  # Thêm sau cho UI đẹp hơn (tùy chọn)
  fluttertoast: ^8.2.4  # Hiển thị thông báo
  loading_animation_widget: ^1.2.0+4  # Loading spinner
  image_picker: ^1.2.0
  video_player: ^2.10.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
