
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvPd_JLGFlHVyJ3WR2eCyy1YtCaHTuJ-o',
    appId: '1:655103036581:web:340738ae9bf7ae0425514c',
    messagingSenderId: '655103036581',
    projectId: 'goiymonan-e8fba',
    authDomain: 'goiymonan-e8fba.firebaseapp.com',
    storageBucket: 'goiymonan-e8fba.firebasestorage.app',
    measurementId: 'G-DVC9S6TSWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtK9TcwPTexCe4MiETVDw4qnU_oVq-hGY',
    appId: '1:655103036581:android:97757cbd55dd96f225514c',
    messagingSenderId: '655103036581',
    projectId: 'goiymonan-e8fba',
    storageBucket: 'goiymonan-e8fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygIm8NtiJwkK1ynFlENRrjLS0ji-lAmM',
    appId: '1:655103036581:ios:da88e961c567ce7025514c',
    messagingSenderId: '655103036581',
    projectId: 'goiymonan-e8fba',
    storageBucket: 'goiymonan-e8fba.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygIm8NtiJwkK1ynFlENRrjLS0ji-lAmM',
    appId: '1:655103036581:ios:da88e961c567ce7025514c',
    messagingSenderId: '655103036581',
    projectId: 'goiymonan-e8fba',
    storageBucket: 'goiymonan-e8fba.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvPd_JLGFlHVyJ3WR2eCyy1YtCaHTuJ-o',
    appId: '1:655103036581:web:5180f81dd1ff73de25514c',
    messagingSenderId: '655103036581',
    projectId: 'goiymonan-e8fba',
    authDomain: 'goiymonan-e8fba.firebaseapp.com',
    storageBucket: 'goiymonan-e8fba.firebasestorage.app',
    measurementId: 'G-Z1BBMKLL8J',
  );

}